config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'creative_escapes#index'
  resources :creative_escapes, only: [:index, :show, :new, :create, :edit, :update]
  resources :bookings, only: [:show, :create] do
  resources :payments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  monetize :amount_cents

end

app/models/creative_escape.rb
class CreativeEscape < ApplicationRecord
  has_many :escape_photos, dependent: :destroy
  geocoded_by :full_address
  after_validation :geocode
  monetize :price_cents
  include PgSearch
  pg_search_scope :search_by_description_and_country, against: [:description, :country, :city]

  def full_address
    "#{streetnumber} #{address} #{city} #{postcode} #{country}"
  end

  def previous
    CreativeEscape.where("id < ?", self.id).first
  end

  def next
    CreativeEscape.where("id > ?", self.id).first
  end
end

app/models/escape_photo.rb
class EscapePhoto < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :creative_escape, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # def authenticate_admin!

  #   redirect_to new_user_session_path unless current_user.is_admin?
  # end

private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    skip_authorization
    @creative_escape = CreativeEscape.find(params[:creative_escape_id])
    booking  = Booking.create!(sku: @creative_escape.sku, amount: @creative_escape.price, state: 'pending')
    redirect_to new_booking_payment_path(booking)
  end

  def show
    skip_authorization
    @booking = Booking.where(state: 'paid').find(params[:id])
  end

end

app/controllers/creative_escapes_controller.rb
class CreativeEscapesController < ApplicationController

  def index
    if params[:search].nil?
       @creative_escapes = policy_scope(CreativeEscape)
    else
      @creative_escapes = CreativeEscape.search_by_description_and_country(params[:search])
    end
    @creative_escapes_maps = CreativeEscape.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@creative_escapes) do |creative_escape, marker|
    marker.lat creative_escape.latitude
    marker.lng creative_escape.longitude
    end
  end

  def show
    skip_authorization
    @creative_escape = CreativeEscape.find(params[:id])
    @previous = @creative_escape.previous
    @next = @creative_escape.next
    @hash = Gmaps4rails.build_markers([@creative_escape]) do |creative_escape, marker|
      marker.lat creative_escape.latitude
      marker.lng creative_escape.longitude

    end
  end

  def new
    #user.admin?
    @creative_escape = CreativeEscape.new
  end

  def create
    @creative_escape = CreativeEscape.create(creative_escape_params)
      params[:creative_escape][:escape_photos].each do |escape_photo|
        new_photo = @creative_escape.escape_photos.create!(photo: escape_photo)
        end
    redirect_to creative_escape_path(@creative_escape)
  end

  def edit
    @creative_escape = CreativeEscape.find(params[:id])
    authorize @creative_escape
  end

  def update
    authorize @creative_escape
    @creative_escape = CreativeEscape.find(params[:id])

    if @creative_escape.update(creative_escape_params)
      redirect_to creative_escape_path(@creative_escape)
    else
      render :edit
    end
  end

  def delete
    authorize @creative_escape

  end


  private

  def creative_escape_params
    params.require(:creative_escape).permit(:description, :escape_photos, :length,:price_cents,
      :currency, :streetnumber, :address, :postcode, :city, :country, :email, :phone, :skill)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :index, :show ]

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
 before_action :set_booking
 before_action :authenticate_user!, only:[:new]

  def new
    skip_authorization
  end

  def create
    skip_authorization
    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
  )

  charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @booking.amount_cents, # or amount_pennies
    description:  "Payment for Creative Escape #{@booking.sku} for booking #{@booking.id}",
    currency:     @booking.amount.currency
  )

  @booking.update(payment: charge.to_json, state: 'paid')
  redirect_to booking_path(@booking)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_booking_payment_path(@booking)
  end

private

  def set_booking
    @booking = Booking.where(state: 'pending').find(params[:booking_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
  @user = User.new
end

 def update
    @user = User.find(params[:id])
    @user.update(user_params)
 end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div class="container" style="min-height: 525px">
    <div class="col-xs-8 col-sm-8">
    <h1></h1>
    <h1></h1>
      <div class = "well">
        <h1>Here is your booking</h1>
          <ul>
            <li>Status: <%= @booking.state %></li>
            <li>Item: <%= @booking.sku %></li>
            <li>Amount: <%= humanized_money_with_symbol(@booking.amount) %></li>
          <ul>
    </div>
 </div>
</div>

app/views/creative_escapes/_form.html.erb
        <%= simple_form_for @creative_escape do |f| %>
        <%= f.input :skill %>
        <%= f.input :description %>
        <%= f.input :length %>
        <%= f.input :price_cents %>
        <%= f.input :currency %>
        <%= f.input :streetnumber %>
        <%= f.input :address %>
        <%= f.input :postcode %>
        <%= f.input :city %>
        <%= f.input :country %>
        <%= f.input :email %>
        <%= f.input :phone %>
        <%= f.input :escape_photos, as: :file, input_html: { multiple: true } %>
        <%= f.input :sku %>
        <%= f.submit %>
        <% end %>

app/views/creative_escapes/edit.html.erb
<div class="container">
 <div class="row" >
    <div class="col-xs-8 col-sm-8">
     <div class = "well">
        <%= render 'form' %>
          <div class="pull-right">
            <%= submit_tag 'delete', class: 'btn btn-primary'%>
          </div>
        <h1> </h1>
     </div>
    </div>
 </div>
</div>

app/views/creative_escapes/index.html.erb
<div class="container" >
  <h1>Creative Escapes</h1>
  <div style="min-height: 550px">
      <!-- <form action="" class="navbar-wagon-search">
        <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
        <button type="submit" class="navbar-wagon-search-btn">

        </button>
      </form> -->
  <%= form_tag creative_escapes_path, method: :get, class:'navbar-wagon-search' do  %>
  <%= text_field_tag :search%>
  <%= submit_tag "search", class: "navbar-wagon-search-btn" %>
   <%end %>


    <div style="min-height: 35px"></div>
    <div class="row">
      <% @creative_escapes.each do |creative_escape| %>
        <div class="col-xs-12 col-sm-4">
           <%= link_to creative_escape_path(creative_escape), style:"text-decoration: none;" do %>
         <div class="contour">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path creative_escape.escape_photos.first.photo %>')">
               <div class="card-category"><%= creative_escape.city%></div>
               <div class="card-description"></div>
            </div>
               <p><%= creative_escape.skill%></p>
          </div>
          <div style="min-height: 35px"></div>
             <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/creative_escapes/new.html.erb
<div class="container">
 <div class="row" >
    <div class="col-xs-8 col-sm-8">
     <div class = "well">
        <%= simple_form_for @creative_escape do |f| %>
          <%= f.input :description %>
          <%= f.input :length %>
          <%= f.input :price %>
          <%= f.input :currency %>
          <%= f.input :streetnumber %>
          <%= f.input :address %>
          <%= f.input :postcode %>
          <%= f.input :city %>
          <%#= f.input :country %>
          <%= f.input :email %>
          <%= f.input :phone %>
          <%= f.input :escape_photos, as: :file, input_html: { multiple: true } %>
          <%= f.submit %>
          <% end %>
      </div>
    </div>
 </div>
</div>

app/views/creative_escapes/show.html.erb
<div class="container">

  <h1><%= @creative_escape[:skill] %> in <%= @creative_escape[:city] %></h1>

  <div class="row" >
    <div class="col-sm-12" >
    <div class="header-show" style="background-image: url('<%= cl_image_path @creative_escape.escape_photos.first.photo %>');">

    </div>
    </div>
  </div>


  <div class="row">
    <div class="col-sm-4" class="text-justify">
    <div class = "well">
          <h2> info </h2>

            <p>price range: <%= humanized_money_with_symbol(@creative_escape.price) %>
            duration: <%= @creative_escape[:length] %></p>
            <p>contact:
            </p>
            <p><%= @creative_escape[:streetnumber] %> <%= @creative_escape[:address] %>
            <%= @creative_escape[:postcode] %> <%= @creative_escape[:city] %> <%= @creative_escape[:country] %>
            <%= @creative_escape[:email]%>
            <%= @creative_escape[:phone] %></p>
            <%= form_tag bookings_path do %>
            <%= hidden_field_tag 'creative_escape_id', @creative_escape.id %>
              <div class="pull-right">
              <%= submit_tag 'Booking', class: 'btn btn-primary'%>
              </div>
            <% end %>
            <p></p>
            <p></p>


          <div id="map" style="width: 235px; height: 300px;"></div>

      <% content_for(:after_js) do %>
        <%= javascript_tag do %>
          $(document).ready(function() {
            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function() {
              markers = handler.addMarkers(<%= raw @hash.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(14);
              }
            });
          });
        <% end %>
      <% end %>

      </div>
    </div>

    <div class="col-sm-8" >
        <div class= "description" style="min-height: 300px">
          <h2> description</h2>
            <%= simple_format @creative_escape[:description] %>
              <div class="pull-right">
                <p><%=link_to "previous escape |",creative_escape_path(@previous) if @previous %> <%= link_to "back to list", creative_escapes_path %>
                  <%= link_to "| next escape",creative_escape_path(@next) if @next %></p>
              </div>
        </div>
    </div>
  </div>

  <div class="row">
      <% @creative_escape.escape_photos.each do |escape_photo| %>
        <div class=" col-sm-3">
          <%= cl_image_tag escape_photo.photo, height: 300, width: 220, crop: :fill, class:"images" %>
        </div>

      <% end %>

  </div>

  <div class="row" >
  <div class="col-sm-12">
    <%= link_to "Edit", edit_creative_escape_path(@creative_escape), class: "btn btn-primary" %>
    </div>
  </div>

  <div class="row" >
  <div class="col-sm-12">

  </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
      <%#= cl_image_tag("test", width: 1300, height: 150, crop: :fill) %>
     <%= render 'shared/navbar' %>
     <%= render 'shared/flashes' %>
     <%= yield %>
     <%= render 'shared/footer' %>
  <!-- #content -->
    <!-- #footer -->
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=AIzaSyBY1BuREvixwUlX-DqYMmD9qMxtXlX3AZA" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

     <%= javascript_include_tag 'application' %>
  <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<div class="col-sm-8" >
 <div class="text-justify">
  <h2> description</h2>

  </div>

app/views/payments/new.html.erb
<div class= "container" style="min-height: 525px">
    <div class="col-xs-8 col-sm-8">
      <h1> </h1>
      <h1> </h1>

      <div class = "well">
          <h1>Booking a Creative Escape <%= @booking.sku %></h1>
          <%= form_tag booking_payments_path(@booking) do %>
            <article>
              <label class="amount">
                <span>Amount: <%= humanized_money_with_symbol(@booking.amount) %></span>
              </label>
            </article>

            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-name="My Creative Escape"
              data-email="<%= current_user.email %>"
              data-description="CreativeEscape <%= @booking.sku %>"
              data-amount="<%= @booking.amount_cents %>"
              data-currency="<%= @booking.amount.currency %>"></script>

            <% end %>
        </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <ul>
       <a href  class="fa fa-facebook-square" ></a>
      <a href class="fa fa-twitter" aria-hidden="true"></a>
      <a href class="fa fa-instagram" aria-hidden="true"></a>
      <a>general conditions</a>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= cl_image_tag("yugen2", width: 50, height: 50, crop: :fill) %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
<!--       <%= link_to t(".", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %> -->
      <%= link_to t(".", default: "Sign In"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%#= link_to "login", new_user_session_path, class: "btn btn-default" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>